### ISSUE TITLE
词频：半淞园路 鲅鱼

### ISSUE THREAD

**Issue by gaboolic** [hugh7007/xmjd6-rere#12]
bsyl目前是半淞园路，
鲅鱼 理应占据bsyl

**Comment by gaboolic** [comment]
查了下 『半淞园路』是上海的一条街道，1km的小街道
就连上海 ephhi  都没占据4码 
半淞园路 何德何能占据4码

**Comment by gaboolic** [comment]
调词频是怎样的流程？

**Comment by linGinc** [comment]
现在是增加了 附加词 的词库，很多三码的地名就不好用了，比如经常做合同或者输入地名，之前北京是 bwj，现在是bwji，新的bwj是个补差价，再比如上海 eph，现在是ephhi。你可以看下不行把附加词库关了，然后使用下自定义user词库，弄下自己的词
