### ISSUE TITLE
i模式bug：输入ifcitx 出现“同学”

### ISSUE THREAD

**Issue by gaboolic** [hugh7007/xmjd6-rere#13]
ifcitx
会变为：  fci同学

![image](https://github.com/hugh7007/xmjd6-rere/assets/3831173/a6d8088c-6052-4fc1-86ce-162c45caf84e)

**Comment by gaboolic** [comment]
我希望i模式能一直输入英文

**Comment by 0x696c757a696f** [comment]
检查输入法的问题

**Comment by gaboolic** [comment]
> 检查输入法的问题

你要不要试一下？
我在电脑和手机端都有这个问题，你直接“检查输入法的问题”然后close issue？

**Comment by gaboolic** [comment]
![Uploading Screenshot_2024-04-12-09-51-01-58_ae1f93045b87aacac90efbb155289789.jpg…]()
![Uploading Screenshot_2024-04-12-09-51-04-57_ae1f93045b87aacac90efbb155289789.jpg…]()

**Comment by gaboolic** [comment]
![8f0fa93096835e35e7e22b6eedf3e9c9](https://github.com/hugh7007/xmjd6-rere/assets/3831173/2df8792d-0874-45e7-8043-0dc61f4516f1)

**Comment by gaboolic** [comment]
![496342b22bc839d46dde6175f36230bf](https://github.com/hugh7007/xmjd6-rere/assets/3831173/de09e792-69a4-4a33-aae9-21eb3f36804b)

**Comment by gaboolic** [comment]
更新到 2024.04.09 词库更新  版本没有此问题
