### ISSUE TITLE
新版注释掉ico那行，显示的还是猫的图标，配置没有生效

### ISSUE THREAD

**Issue by linGinc** [hugh7007/xmjd6-rere#15]
已经注释掉了，并重新部署，还是显示猫的图标
![image](https://github.com/hugh7007/xmjd6-rere/assets/16556351/bb4ebce3-8909-4ff3-a467-e5a07ec98b22)

**Comment by 0x696c757a696f** [comment]
需要 ctrl+` 重新选择一下方案
