### ISSUE TITLE
目前功能把avuio键都占用了，不太方便自己的一些词库

### ISSUE THREAD

**Issue by linGinc** [hugh7007/xmjd6-rere#2]
目前新更新的把avuio键都使用上了，自己的一些之前弄的快捷输入键没有办法快速输入了：
如：
我之前用o键开始启用一些自己常用邮箱还有开票信息一些的信息，目前都不能快速读入了
omo：xxxx@outlook.com omq：xxxxxxxx@qq.com
ogp：1234567890（公司的税号）
ogk：邮寄地址：xxxx，姓名：xxxxx，电话：xxxxxxx

**Comment by 0x696c757a696f** [comment]
xmjd6.schema.yaml 里将 "pinyin_simp_lookup: "开始到" xmjdWW: "所有行都注释掉，就可以关闭星猫 avuio 的功能。

如果只需要关闭星猫 o 的功能，只需要注释 "xmjd6gbk: "的内容 
![图片](https://github.com/hugh7007/xmjd6-rere/assets/39948247/a3b4edc1-2ff9-497c-b704-4b81525b0420)

**Comment by 0x696c757a696f** [comment]
关于o不能沿用之前功能是考虑进一步优化，如果需要内置个人信息，
更偏向于放入
 xmjd6.lianjie.dict.yaml

或者放入   
 xmjd6.user.dict.yaml
理由：因为o与v 是直接调用的单独8万多的字集，之前为了打表情，就排除了o与v 直接显示2字 3字的字母
不会显示对应的文字，而是显示自定义添加相应的内容<如果不添加，对应的字母显示为空>

如果实在喜欢自定义，可以选择  ;+字母  → 例如：;yx ;fp ;df  等等 组合来调用邮箱之类的 
;yx  邮箱
;fp   发票
;df   地址

**Comment by linGinc** [comment]
谢谢指导，如果保留O的话，手机打;yx这个就没有办法打了，你有啥好想法么

**Comment by 0x696c757a696f** [comment]
> 谢谢指导，如果保留O的话，手机打;yx这个就没有办法打了，你有啥好想法么

可以在xmjd6.gbk.dict.yaml里加需要的。这里都是o开头的。
