### ISSUE TITLE
在 #20240104 版本中无法设置竖排

### ISSUE THREAD

**Issue by ker-j** [hugh7007/xmjd6-rere#3]
在`pinyin_simp.schema.yaml`和`squirrel.custom.yaml`这两个文件里所有`horizontal`都设置了`horizontal: false`，但是重新部署后都无法显示竖排显示，依旧是横排。在之前的版本是没问题的。

### 使用环境

* 系统：win11
* 版本：weasel 0.15.0

### 最后

习惯了竖排所以就来提了个 `issues`。另外——很喜欢这个项目，新出的版本皮肤都很喜欢，非常感谢。

**Comment by linGinc** [comment]
同样，在weasel.custom.yaml 里的皮肤没有horizontal:false, 参数，自己手动添加也不行

**Comment by hugh7007** [comment]
打开

xmjd6.schema.yaml 

拉到最下面
style:
   horizontal: false #竖排为false横为true

**Comment by hugh7007** [comment]
> 同样，在weasel.custom.yaml 里的皮肤没有horizontal:false, 参数，自己手动添加也不行

打开   xmjd6.schema.yaml  拉到最下面

style:
   horizontal: false #竖排为false横为true

**Comment by 0x696c757a696f** [comment]
目前相关设置已移到 xmjd6.custom.yaml 中。
