### ISSUE TITLE
词频更新建议

### ISSUE THREAD

**Issue by linGinc** [hugh7007/xmjd6-rere#4]
老实 lzek
老师 lzeku

从我和旁边使用键道𝟲的几个同事使用频率来说，老师使用频率要比老实多，建议把老师词频提升至首位

**Comment by 0x696c757a696f** [comment]
可以使用最新release版本

**Comment by 0x696c757a696f** [comment]
可以用下最新Release版本：[2024.01.29 词库更新](https://github.com/hugh7007/xmjd6-rere/releases/tag/20240129)
